### ISSUE TITLE
Duplicated elements in types list

### ISSUE THREAD

**Issue by Cerberuser** [mulesoft-labs/api-console-cli#30]
Greetings!

I've just run into some strange behaviour with `api-console-cli`. Here's my RAML (simplified as much as possible):

api.raml
```
#%RAML 1.0
title: Test
mediaType: application/json
uses:
    lib: lib.raml
/endpoint:
    post:
        body: lib.Type1
```

lib.raml
```
#%RAML 1.0 Library
types:
    Type1:
        properties:
            field1: string
    Type2:
        type: Type1
        properties:
            field2: number
```

When console is built, there are three types in "Types" part of the sidebar: two instances of `Type1` and one - of `Type2`. Seems that this example is minimal possible: removing endpoint or `mediaType` or moving type definitions into `api.raml` disables the anomaly.
